from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class MatchStatus(str, Enum):
    exact_match = "exact_match"
    near_duplicate = "near_duplicate"
    new_material = "new_material"
    uncertain = "uncertain"


class LineItem(BaseModel):
    """A line as returned by OCR / barcode lookup and edited in the UI. Deliberately lenient:
    validation happens when the operator confirms the receipt (see ConfirmLineItem)."""
    line_id: str
    description: str
    quantity: float
    unit: str
    unit_price: float
    total_price: float
    batch_number: Optional[str] = None
    hsn_code: Optional[str] = None
    match_status: MatchStatus = MatchStatus.new_material
    matched_material_id: Optional[str] = None
    matched_description: Optional[str] = None
    # Id of the pending material created for this line during OCR (None when the line was
    # auto-linked to an existing material). Stock is booked against it on confirmation.
    pending_material_id: Optional[str] = None
    confidence: float = 0.0
    match_reason: Optional[str] = None
    cnmc: Optional[str] = None
    is_new_material: bool = True
    quality_grade: Optional[str] = ""
    quality_notes: Optional[str] = ""
    location_code: Optional[str] = None
    vendor_id: Optional[str] = None
    barcode: Optional[str] = None
    expiry_date: Optional[date] = None


class OCRResponse(BaseModel):
    receipt_id: str
    line_items: List[LineItem]
    bill_image_url: Optional[str] = None   # short-lived signed URL, for preview only
    bill_image_path: Optional[str] = None  # permanent storage reference to send back on confirm


class BarcodeRequest(BaseModel):
    code: str = Field(min_length=1, max_length=128)


class ConfirmLineItem(BaseModel):
    """A line as accepted when confirming a receipt. Mirrors the database constraints so bad
    input is rejected with a readable 422 instead of failing halfway through the write."""
    line_id: str
    description: str = Field(min_length=1, max_length=500)
    quantity: float = Field(gt=0, le=999_999_999)
    unit: str = Field(min_length=1, max_length=20)
    unit_price: float = Field(ge=0, le=99_999_999)
    batch_number: Optional[str] = Field(default=None, max_length=100)
    hsn_code: Optional[str] = Field(default=None, max_length=50)
    match_status: MatchStatus = MatchStatus.new_material
    matched_material_id: Optional[str] = None
    pending_material_id: Optional[str] = None
    quality_grade: Literal["A", "B", "C"]
    quality_notes: Optional[str] = Field(default=None, max_length=500)
    location_code: str = Field(min_length=1, max_length=100)
    barcode: Optional[str] = Field(default=None, max_length=128)
    expiry_date: Optional[date] = None


class ConfirmRequest(BaseModel):
    vendor_id: str
    receipt_date: date
    po_number: Optional[str] = Field(default=None, max_length=100)
    bill_image_path: Optional[str] = Field(default=None, max_length=300)
    # Generated by the client per draft receipt; makes a retried request return the receipt
    # that was already created instead of creating a second one.
    client_draft_id: Optional[str] = Field(default=None, max_length=64)
    line_items: List[ConfirmLineItem] = Field(min_length=1, max_length=500)


class ConfirmResponse(BaseModel):
    receipt_id: str
    gr_number: str
    status: str
    line_items_created: int
    total_value: float
    already_confirmed: bool = False
