from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, List, Literal, Optional

from pydantic import BaseModel, Field


class MatchStatus(str, Enum):
    exact_match = "exact_match"
    near_duplicate = "near_duplicate"
    new_material = "new_material"
    uncertain = "uncertain"


class LineItem(BaseModel):
    """A line as returned by OCR / barcode lookup and edited in the UI.

    Plan D-6 (decided 2026-09-22): OCR is a read-only draft. Nothing here has been written to the
    database yet — no material, no matching_queue row. Exactly two things distinguish how a line
    is booked at confirm time:
      * material_id set -> this line links to a material that already exists (an auto-linked exact
        match, a barcode hit, or later an operator-picked one). No material is created for it.
      * material_id unset -> this line needs a brand-new ('pending') material, using the
        classification fields below, created as part of the same transaction that confirms the
        receipt. candidate_material_id (if set) is only informational until confirm, where it
        becomes a matching_queue row for review.
    Deliberately lenient otherwise: validation happens when the operator confirms the receipt (see
    ConfirmLineItem).
    """
    line_id: str
    description: str
    quantity: float
    unit: str
    unit_price: float
    total_price: float
    batch_number: Optional[str] = None
    hsn_code: Optional[str] = None
    match_status: MatchStatus = MatchStatus.new_material
    # Set only when this line links directly to an existing material (see class docstring).
    material_id: Optional[str] = None
    is_new_material: bool = True
    quality_grade: Optional[str] = ""
    quality_notes: Optional[str] = ""
    location_code: Optional[str] = None
    vendor_id: Optional[str] = None
    barcode: Optional[str] = None
    expiry_date: Optional[date] = None

    # -- candidate (informational until confirm; becomes a matching_queue row then) --
    candidate_material_id: Optional[str] = None
    matched_description: Optional[str] = None
    match_type: Optional[str] = None
    confidence: float = 0.0
    vector_similarity: float = 0.0
    match_reason: Optional[str] = None

    # -- draft classification for a brand-new material (present when material_id is None) --
    cnmc: Optional[str] = None
    category: Optional[str] = None
    subcategory: Optional[str] = None
    material_type: Optional[str] = None
    spec: Optional[str] = None
    standard_description: Optional[str] = None
    short_description: Optional[str] = None
    technical_specs: Optional[dict[str, Any]] = None


class OCRResponse(BaseModel):
    receipt_id: str
    line_items: List[LineItem]
    bill_image_url: Optional[str] = None   # short-lived signed URL, for preview only
    bill_image_path: Optional[str] = None  # permanent storage reference to send back on confirm


class BarcodeRequest(BaseModel):
    code: str = Field(min_length=1, max_length=128)


class ConfirmLineItem(BaseModel):
    """A line as accepted when confirming a receipt. Mirrors LineItem's fields (the UI forwards
    whatever OCR/barcode returned, edited in place) plus the database constraints, so bad input is
    rejected with a readable 422 instead of failing halfway through the write."""
    line_id: str
    description: str = Field(min_length=1, max_length=500)
    quantity: float = Field(gt=0, le=999_999_999)
    unit: str = Field(min_length=1, max_length=20)
    unit_price: float = Field(ge=0, le=99_999_999)
    batch_number: Optional[str] = Field(default=None, max_length=100)
    hsn_code: Optional[str] = Field(default=None, max_length=50)
    match_status: MatchStatus = MatchStatus.new_material
    material_id: Optional[str] = None
    quality_grade: Literal["A", "B", "C"]
    quality_notes: Optional[str] = Field(default=None, max_length=500)
    location_code: str = Field(min_length=1, max_length=100)
    barcode: Optional[str] = Field(default=None, max_length=128)
    expiry_date: Optional[date] = None

    candidate_material_id: Optional[str] = None
    match_type: Optional[str] = None
    confidence: float = 0.0
    vector_similarity: float = 0.0
    match_reason: Optional[str] = None

    cnmc: Optional[str] = None
    category: Optional[str] = None
    subcategory: Optional[str] = None
    material_type: Optional[str] = None
    spec: Optional[str] = None
    standard_description: Optional[str] = None
    short_description: Optional[str] = None
    technical_specs: Optional[dict[str, Any]] = None


class ConfirmRequest(BaseModel):
    vendor_id: str
    receipt_date: date
    po_number: Optional[str] = Field(default=None, max_length=100)
    bill_image_path: Optional[str] = Field(default=None, max_length=300)
    # Generated by the client per draft receipt; makes a retried request return the receipt
    # that was already created instead of creating a second one.
    client_draft_id: Optional[str] = Field(default=None, max_length=64)
    line_items: List[ConfirmLineItem] = Field(min_length=1, max_length=500)


class ConfirmResponse(BaseModel):
    receipt_id: str
    gr_number: str
    status: str
    line_items_created: int
    total_value: float
    already_confirmed: bool = False
